name: Build Extension

on:
    push:
      branches:
        - main
      paths-ignore: # dont run when changes made to these folders
        - '.vscode/**'

jobs:
    build:
        name: Build Extension
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                submodules: recursive

            # - name: install gitversion tool
            #   uses: gittools/actions/gitversion/setup@v0.10.2
            #   with:
            #         versionSpec: '5.x'

            # - name: execute gitversion
            #   id: gitversion # step id used as reference for output values
            #   uses: gittools/actions/gitversion/execute@v0.10.2

            # - name: print gitversion
            #   run: |
            #     echo "Major: ${{ steps.gitversion.outputs.major }}"
            #     echo "Minor: ${{ steps.gitversion.outputs.minor }}"
            #     echo "Patch: ${{ steps.gitversion.outputs.patch }}"
            #     echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"
            #     echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"

            - name: Install Node
              uses: actions/setup-node@v3
              with:
                node-version: '24'

            - name: Install Packages
              working-directory: BitMagic.VscExtension
              run: npm install

            - name: Install TypeScript
              working-directory: BitMagic.VscExtension
              run: npm install -g typescript

            - name: Install VSCE
              working-directory: BitMagic.VscExtension
              run: npm install -g @vscode/vsce

            - name: Install OVSX
              working-directory: BitMagic.VscExtension
              run: npm install -g ovsx

            - name: Install Win-Node-Env
              working-directory: BitMagic.VscExtension
              run: npm install -g win-node-env

            - name: Compile Extension
              working-directory: BitMagic.VscExtension
              run: node ./esbuild.js

            - name: Compile and Create VSIX
              working-directory: Bitmagic.VscExtension
              run: vsce package

            - name: Publish
              working-directory: Bitmagic.VscExtension
              run: vsce publish -p ${{ secrets.VSCODEDEPLOY }}

            - name: Publish VSCodium
              working-directory: Bitmagic.VscExtension
              run: npx ovsx publish -p ${{ secrets.VSCODIUM }}
